import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { MantineProvider } from "@/components/providers/MantineProvider";
import { ServiceWorkerProvider } from "@/components/providers/ServiceWorkerProvider";
import "./globals.css";
import { strings } from "@/lib/i18n/strings";

// Self-hosted at build time: no render-blocking request to Google Fonts, and
// the font is served from /_next/static so it works offline too.
const inter = Inter({
  subsets: ["latin", "latin-ext"],
  display: "swap",
  variable: "--font-inter",
  preload: true,
});

export const metadata: Metadata = {
  // `template` gives every child title a suffix ("Log Masuk · EasyHC")
  title: {
    default: strings.appName,
    template: `%s · ${strings.appName}`,
  },
  description: strings.appDescription,
  manifest: "/manifest.json",
  applicationName: strings.appName,
  // Generated by scripts/generate-icons.ts — the previous raw <link> tags
  // pointed at files that did not exist (404s for favicon and the iOS icon).
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/icons/icon-192x192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: "/icons/apple-touch-icon.png",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: strings.appName,
  },
  // Shared into WhatsApp/Teams/Slack previews — the visitor QR link is
  // circulated as a plain URL, so the preview should not be blank.
  openGraph: {
    type: "website",
    locale: "ms_MY",
    siteName: strings.appName,
    title: strings.appName,
    description: strings.appDescription,
  },
  twitter: {
    card: "summary",
    title: strings.appName,
    description: strings.appDescription,
  },
};

// Next 14: viewport/themeColor belong in their own export, otherwise they
// trigger "Unsupported metadata ..." warnings on every route.
// userScalable/maximumScale are deliberately omitted: pinching to zoom is
// required by WCAG 1.4.4 (Resize Text).
export const viewport: Viewport = {
  themeColor: "#2563eb",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ms" className={inter.variable} suppressHydrationWarning>
      <head>
        <meta name="mobile-web-app-capable" content="yes" />
      </head>
      <body>
        <MantineProvider>{children}</MantineProvider>
        {/* Registers /sw.js (production) and announces online/offline */}
        <ServiceWorkerProvider />
      </body>
    </html>
  );
}
